[package]
name = "network-regressions"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
copernica-lib = { path = "../copernica-lib" }
logger = { path = "../logger" }
packets = { path = "../packets" }
crossbeam = "0.7"
crossbeam-channel = "0.3"
log = "0.4"
dirs = "2.0.2"
