[workspace]

members = [
    "copernica",
    "ccli",
    "client-libs",
    "network-regressions",
    "logger",
    "copernicafs",
    "transport",
    "copernica-apps",
]

exclude = [
    "chain-libs",
]
