[package]
name = "copernica"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]

bincode = "1"
futures-preview = "0.3.0-alpha.19"
router = { path = "../router" }
faces = { path = "../faces" }
content-store = { path = "../content-store" }
log = "0.4"
env_logger = "0.7.1"

[dev-dependencies]
env_logger = "0.7.1"
