[package]
name = "copernica-common"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.3.0"
fern = "0.5.9"
chrono = "0.4.9"
log = "0.4"
rand = "0.7.2"
sha3 = "0.8.2"
anyhow = "1.0"
