[package]
name = "copernica-broker"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[lib]
name = "copernica_broker"
path = "src/lib.rs"

[dependencies]
copernica-common = { path = "../copernica-common" }
log = "0.4"
crossbeam-channel = "0.3"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
sled = "0.32.0"
