[package]
name = "packets"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
error-chain = "0.11"
bincode = "1"
serde = "1.0.63"
serde_derive = "1.0.27"

[dev-dependencies]
serde_bytes = "0.11"

