[package]
name = "packets"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
error-chain = "0.11"
bincode = "1"
serde = "1.0.63"
serde_derive = "1.0.27"
sha3 = "0.8.2"

[dev-dependencies]
tar = "0.4.26"
flate2 = "1.0.11"
bitvec = "0.15.2"
