[package]
name = "copernica-links"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copernica-common = { path = "../copernica-common" }
copernica-identity= { path = "../copernica-identity" }
async-std = "1.4.0"
crossbeam-channel = "0.3"
anyhow = "1.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
reed-solomon = "0.2"
log = "0.4"
rand = "0.7.2"
rand_core = "0.5.1"
cryptoxide = "0.2.1"
